# Some checks to stop some human errors:
# - checking in AWS secrets, private keys, and other suspicious patterns.
# - ditto for suspicious files, like `.ssh`.
# - prevent direct commit/push to master or production (enforce pull-request hygiene)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: check-added-large-files
      - id: detect-private-key
      - id: pretty-format-json

  - repo: meta
    hooks:
      - id: check-useless-excludes
